### ISSUE TITLE
Oracle mask experiment of Open3DIS on table 5

### ISSUE THREAD

**Issue by cjm-jamie** [aminebdj/OpenYOLO3D#15]
Dear authors,

Thank you for your valuable work and detailed explanations. I have a question regarding the oracle mask experiment for Open3DIS shown on Table 5 in your paper.

Could you please provide more details on how this experiment was set up? Specifically, which part of the Open3DIS framework was replaced with the ground truth (GT) mask to achieve the results in the oracle mask setup?

Thank you very much!

**Comment by aminebdj** [comment]
Hello @cjm-jamie,
 I hope you are doing well,

For oracle masks, we use the ground truth object instance masks provided in the dataset (scannet200 or replica). This experiment tests the ability of the model to annotate class agnostic masks which don't have a class label. This is also to insure a fair comparison with Open3DIS and OpenMask3D in terms of label prediction, since Mask3D proved to generate different masks for every round, thus this introduces a lot of variance from the mask side (Thats why we share the masks to reproduce our results in the paper). By fixing the masks to ground truth, we can easily compare the 3D methods fairly, also we remove any post processing in all methods like the topk class predictions.
