### ISSUE TITLE
About the "text" input during evaluation

### ISSUE THREAD

**Issue by zhixuanli** [aminebdj/OpenYOLO3D#8]
Dear authors,

Thank you for your awesome work and for releasing the code.

I found that at the `run_evaluation.py`, the `text` in the `prediction = openyolo3d.predict()` function is missing. I believe the `text` is necessary since as shown in the network architecture figure of your paper, the input contains the text, which plays an important role in making this method outstanding.

Could you please add the `text` into this function input, or explain this if the `text` is not needed in the evaluation process?

Thank you!

**Comment by aminebdj** [comment]
Dear @zhixuanli,

Thanks for your interest in our work,

The default value of the `text` argument is set to `None` in [this line](https://github.com/aminebdj/OpenYOLO3D/blob/1a01f09cfdd5efe356bf48ece991b5dd7aa12589/utils/__init__.py#L103), afterwords it is passed to [this method](https://github.com/aminebdj/OpenYOLO3D/blob/1a01f09cfdd5efe356bf48ece991b5dd7aa12589/utils/utils_2d.py#L60) in class Network2D where it uses the default [text](https://github.com/aminebdj/OpenYOLO3D/blob/1a01f09cfdd5efe356bf48ece991b5dd7aa12589/pretrained/config_scannet200.yaml#L9) in the config file if `text` value is `None`, since there are 198 classes in scannet200 dataset, the text prompts are defined there; the same thing for Replica dataset.

Hope this answers your question,
best regards

**Comment by zhixuanli** [comment]
Great!

Thanks for your quick response!
